trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build_stage
    displayName: Build
    jobs:
    - job: build_job
      steps:
      - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'website'
          publishLocation: 'pipeline'

  - stage: deploy_stage
    displayName: Deploy
    jobs:
      - deployment: deployment_job
        environment: Production
        displayName: Deploy on Azure
        strategy:
          runOnce:
            deploy:
             steps:
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'sub-vse(dce4a55c-1d65-46ec-bd2b-831801fc6bab)'
                  appType: 'webAppLinux'
                  WebAppName: 'miferracbluegreen'
                  deployToSlotOrASE: true
                  ResourceGroupName: 'blue-green-rg'
                  SlotName: 'preprod'
                  packageForLinux: '$(Pipeline.Workspace)/website/'
                  RuntimeStack: 'DOTNETCORE|6.0'
            routeTraffic:
             steps:
              - task: AzureAppServiceManage@0
                inputs:
                  azureSubscription: 'sub-vse(dce4a55c-1d65-46ec-bd2b-831801fc6bab)'
                  Action: 'Swap Slots'
                  WebAppName: 'miferracbluegreen'
                  ResourceGroupName: 'blue-green-rg'
                  SourceSlot: 'preprod'
            